import "./globals.css";
import type { Metadata } from "next";
import { Actor } from "next/font/google";
import Navbar from "./components/client/Navbar";
import AuthProvider from "./auth/Provider";

const actor = Actor({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={actor.className}>
        <AuthProvider>
          <Navbar />
          <div>{children}</div>
        </AuthProvider>
      </body>
    </html>
  );
}
